# Use a lightweight Node.js image as the base
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

# Expose port 5000
EXPOSE 5000

# Set the environment variable for production
ENV NODE_ENV=production

# Copy the .env file into the image (if required)
COPY .env /app/backend/.env

# Command to run the backend server
CMD ["npm", "start"]
#CMD ["tail", "-f", "/dev/null"]
